### ISSUE TITLE
KeyError in EnergySystem.flows() after dump/restore

### ISSUE THREAD

**Issue by jnnr** [oemof/oemof-solph#742] opened 2021-01-25 15:53 UTC
**Describe the bug**
There is a KeyError in EnergySystem's flows method when called on a EnergySystem that has been dumped and restored: https://github.com/oemof/oemof.network/blob/96648132045837e58b008f114eae88ed66154007/src/oemof/network/energy_system.py#L176-L181

I found it when using `oemof.solph.processing.parameter_as_dict`. Getting the parameters of an EnergySystem is a useful  step, e.g. in postprocessing. 

The respective dictionary (see log below) contains a Bus with the proper name, but does not seem to totally fit. Maybe the EnergySystem is in an inconsistent state after deserialization? Any ideas @oemof-developer, @oemof/oemof-solph?

**To Reproduce**
1. Go to e.g. the basic example https://github.com/oemof/oemof-examples/blob/master/oemof_examples/oemof.solph/v0.4.x/basic_example/basic_example.py
2. insert this line before energysystem.dump() to see that it works
    energysystem.flows()
3. insert the line after energysystem.restore() to see it fail
4. Get an error traceback like this:

> Traceback (most recent call last):
  File "basic_example.py", line 226, in <module>
    solph.processing.parameter_as_dict(energysystem)
  File "oemof-solph/src/oemof/solph/processing.py", line 378, in parameter_as_dict
    flow_data = __separate_attrs(system, True, exclude_none)
  File "oemof-solph/src/oemof/solph/processing.py", line 343, in __separate_attrs
    components = system.flows() if get_flows else system.nodes
  File ".virtualenvs/oemof-solph/lib/python3.6/site-packages/oemof/network/energy_system.py", line 179, in flows
    for source in self.nodes
  File ".virtualenvs/oemof-solph/lib/python3.6/site-packages/oemof/network/energy_system.py", line 180, in <dictcomp>
    for target in source.outputs
  File ".virtualenvs/oemof-solph/lib/python3.6/collections/__init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: "<oemof.solph.network.Bus: 'natural_gas'>"

**Expected behavior**
The method should work after restoring. In particular, it should be possible to use  parameter_as_dict after restoring.

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Python version 3.6.9

**Comment by henhuy** [comment] 2021-01-25 16:34
What do you use for dumping and restoring?

**Comment by jnnr** [comment] 2021-01-25 16:40
energysystem.dump() and energysystem.restore(), like in the basic example.

**Comment by henhuy** [comment] 2021-01-26 13:07
Scheint als würden die outputs nicht korrekt restored, da folgende Zeile den Fehler wirft:
https://github.com/oemof/oemof.network/blob/dev/src/oemof/network/energy_system.py#L178

Denke, dass hat nichts mit der Funktion `parameter_as_dict` zu tun, eher mit dem dump/restore process...?!

**Comment by jnnr** [comment] 2021-01-26 13:10
> Scheint als würden die outputs nicht korrekt restored, da folgende Zeile den Fehler wirft:
> https://github.com/oemof/oemof.network/blob/dev/src/oemof/network/energy_system.py#L178
> 
> Denke, dass hat nichts mit der Funktion `parameter_as_dict` zu tun, eher mit dem dump/restore process...?!

You are right, the KeyError is in the flows() method.

**Comment by henhuy** [comment] 2021-01-26 13:28
sorry for en/de mixup...
Maybe rename issue and assign to some related people?

**Comment by sschlueters** [comment] 2021-01-26 13:33
Hi there, I think I also stumbled upon this problem: https://github.com/oemof/oemof.network/issues/10#issue-742425717

**Comment by henhuy** [comment] 2021-01-26 13:35
This answers your question @jnnr - we can simply close this issue...

Duplicate of https://github.com/oemof/oemof.network/issues/10

**Comment by jnnr** [comment] 2021-01-26 13:36
Ok, if you say so. I just updated the title. But it is the same problem.

**Closed by henhuy** 2021-01-26 13:35 UTC
Labels: bug, help wanted, oemof-solph

**Comment by henhuy** [comment] 2021-01-26 13:38
Maybe you could ask if there is any progress?

**Comment by Bachibouzouk** [comment] 2021-02-01 10:54
According to `__get_item__()` from the `collection` [module](https://github.com/python/cpython/blob/304f9d2622fa4fd0833d60d31ddf7321a6a8141b/Lib/collections/__init__.py#L1053) the exception is raised only if 
```
if key in self.data:
```
is False

[Apparently](https://github.com/oemof/oemof.network/blob/96648132045837e58b008f114eae88ed66154007/src/oemof/network/network.py#L15) the dict used for oemof outputs inherits from `collection.UserDict` (so I guess `source.outputs.data` would display something worth looking into?). Interestingly [`networks.Outputs` overrides](https://github.com/oemof/oemof.network/blob/96648132045837e58b008f114eae88ed66154007/src/oemof/network/network.py#L68) `__delitem__`, `__setitem__` and `__init__`  of `collection.UserDict` but not `__getitem__`. Maybe the solution is to look there?

Sorry I don't have time to look into it further right now, I hope this might help to lead to finding the bug :)

**Comment by jnnr** [comment] 2021-02-01 13:27
> According to `__getitem__()` from the `collection` [module](https://github.com/python/cpython/blob/304f9d2622fa4fd0833d60d31ddf7321a6a8141b/Lib/collections/__init__.py#L1053) the exception is raised only if
> 
> ```
> if key in self.data:
> ```
> 
> is False

Thanks for your feedback. That's right, the `key in self.data` causes the error. As I understand, it calls the `__contains__` method of the dict, which also returns False. However, `key in list(self.data)` returns True.
