### ISSUE TITLE
Energy content of GenericInvestmentStorageBlock shifted by one timestep compared to GenericStorageBlock

### ISSUE THREAD

**Issue by bdietermann** [oemof/oemof-solph#1124] opened 2024-10-15 06:13 UTC
Hi all,

I'm using oemof-solph v0.5.5 and v0.6.0a1 with python3.11 on Windows 10.

The bevhavior of Storages of type ```GenericInvestmentStorageBlock``` and ```GenericStorageBlock``` differ in a way which I presume to be unintended as the timestamp of the storage's energy content is shifted by one timestep.

This behavior can easily be observed using the following code example.
The modelled system includes two storages with the same capacity, which are not allowed to exchange energy, one defined using a ```Investment``` object the other one with a fixed ```nominal_storage_capacity```.
Taking a closer look to the storage content during the simulation timeframe shows that the energy contents are shifted by one timestep.

I suggest applying the behavior of ```GenericStorageBlock``` to ```GenericInvestmentStorageBlock``` as well.

```python
import pandas as pd
import oemof.solph as solph

es = solph.EnergySystem(timeindex=pd.date_range('1/1/2017', periods=4, freq='15min'))
bus = solph.Bus(label='bus')
es.add(bus)
storage_size = 3000

storage1 = solph.components.GenericStorage(label='storage1',
                                           inputs={bus: solph.Flow()},
                                           outputs={bus: solph.Flow(nominal_value=1,
                                                                    max=0)},
                                           loss_rate=0.001,
                                           balanced=False,
                                           initial_storage_level=0.5,
                                           nominal_storage_capacity=storage_size)
es.add(storage1)

storage2 = solph.components.GenericStorage(label='storage2',
                                           inputs={bus: solph.Flow()},
                                           outputs={bus: solph.Flow(nominal_value=1,
                                                                    max=0)},
                                           loss_rate=0.001,
                                           balanced=False,
                                           initial_storage_level=0.5,
                                           nominal_storage_capacity=solph.Investment(ep_costs=1,
                                                                                     existing=storage_size,
                                                                                     maximum=0)
                                           )
es.add(storage2)

om = solph.Model(energysystem=es)
om.solve(solver='gurobi')
results = solph.processing.results(om)
soc1 = solph.views.node(results, 'storage1')['sequences'][(('storage1', 'None'), 'storage_content')] / storage_size
soc2 = solph.views.node(results, 'storage2')['sequences'][(('storage2', 'None'), 'storage_content')] / storage_size
print('Storage 1\n', soc1, '\n\n', 'Storage 2\n', soc2)
```

Console output:
```
Storage 1
 2017-01-01 00:00:00    0.500000
2017-01-01 00:15:00    0.499875
2017-01-01 00:30:00    0.499750
2017-01-01 00:45:00    0.499625
2017-01-01 01:00:00    0.499500
Freq: 15min, Name: ((storage1, None), storage_content), dtype: float64 

 Storage 2
 2017-01-01 00:00:00    0.499875
2017-01-01 00:15:00    0.499750
2017-01-01 00:30:00    0.499625
2017-01-01 00:45:00    0.499500
2017-01-01 01:00:00         NaN
Freq: 15min, Name: ((storage2, None), storage_content), dtype: float64
```

**Comment by p-snft** [comment] 2024-10-15 14:41
Thanks for reporting. The problem is fixed in dev. The fix was the reason to release v0.6.0a1 but probably, the tag was created to early to contain the fix.

Long story short: I just [released v0.6.0a2](https://pypi.org/project/oemof.solph/0.6.0a2/), that contains the fix.

**Closed by p-snft** 2024-10-15 14:41 UTC
